<?php
	include "../util/session-set.php";
	require('../fpdf181/fpdf.php');
	require('../fpdf181/transform.php');
	
	class PDF extends PDF_Transform{
		function dbConnect(){
			include "../util/dbconn.php";
			return $conn;
		}
		function Header(){
			$this->Ln(10);
			$this->Image('../assets/img/ub.png',112,5,0,18);
			$this->Ln(10);
			
			$str = "University of Baguio High School";
			$this->SetFont('Arial','B',14);
			$this->Cell(0,0,$str,0,0,'C',false);
			$this->Ln(7);
			
			$str = "Schoolyear 2016-2017";
			$this->SetFont('Arial','B',10);
			$this->Cell(0,0,$str,0,0,'C',false);
			$this->Ln(7);
			
			$str = "Student ".$_SESSION["formtype"];
			$this->SetFont('Arial','',10);
			$this->Cell(0,0,$str,0,0,'C',false);
			$this->Ln(25);
		}
		function Footer(){
			$this->SetY(-15);
			$this->SetFont('Arial','I',8);
			$this->Cell(0,10,'Page '.$this->PageNo()." of {nb}",0,0,'C');
			$this->SetFont('Arial','',8);
			$this->Cell(0,10,'Report Generated By: '.$_SESSION["FullName"],0,0,'R');
			
		}
		function StudentAttendanceDetails(){
			$str = "Student Name: ".$_SESSION["FullName"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'L',false);
			
			$this->Cell(20);
			$str = "ID Number: ".$_SESSION["UserID"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
			
			$this->Cell(20);
			$str = "Section: ".$_SESSION["Section"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
					
			$this->Cell(20);
			$str = "Grade/Year: #";
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
			
			$this->Cell(20);
			if (!isset($_SESSION["StartDate"]) && !isset($_SESSION["EndDate"])){
				$str = "Records from: ".date('m/j/Y')." to 08/01/2016";
			}elseif($_SESSION["SelectedGP"] != "All"){
				$str = "Grading Period: ".$_SESSION["SelectedGP"];
			}else{
				$str = "Records from: ".$_SESSION["EndDate"]." to ".$_SESSION["StartDate"];
			}
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
			$this->Ln(20);
		}
		function StudentAttendanceTable(){
			$colWidth = 33;
			$this->SetFont('Arial','B',10);
			$this->Cell($colWidth,0,'DATE/SUBJECTS',0,0,'C');
			$this->Cell($colWidth,0,'AP',0,0,'C');
			$this->Cell($colWidth,0,'Comp. Ed.',0,0,'C');
			$this->Cell($colWidth,0,'English',0,0,'C');
			$this->Cell($colWidth,0,'Filipino',0,0,'C');
			$this->Cell($colWidth,0,'MAPEH',0,0,'C');
			$this->Cell($colWidth,0,'Math',0,0,'C');
			$this->Cell($colWidth,0,'Science',0,0,'C');
			$this->Cell($colWidth,0,'TLE',0,0,'L');
			$this->Line(0,92,$this->GetPageWidth(),92);
			$this->Ln();
			
			$conn = $this->dbConnect();
			$result = $conn->query($_SESSION["sql"]);
			
			$this->SetFont('Arial','',10);
			
			$prevDate = "";
			$genAve = "";
			
			if ($result->num_rows > 0){		
				while($row = $result->fetch_assoc()){
					if($row["AttendanceDate"] != $prevDate){
						$this->Ln(6);
						$this->Cell($colWidth,0,$row["AttendanceDate"],0,0,'L');
					}
					$this->Cell($colWidth,0,$row["AttendanceDescription"],0,0,'L');
					$prevDate = $row["AttendanceDate"];
				}
			}else{
				$this->Ln(50);
				$this->Cell($this->GetPageWidth(),0,'No records.',0,0,'C');
			}
			
		}
		function StudentCsDetails(){
			$str = "Student Name: ".$_SESSION["FullName"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'L',false);
			
			$this->Cell(10);
			$str = "ID Number: ".$_SESSION["UserID"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
			
			$this->Cell(10);
			$str = "Subject: ".$_SESSION["SelectedSubject"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
			
			$this->Cell(10);
			$str = "Section: ".$_SESSION["Section"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
					
			$this->Cell(10);
			if (!isset($_SESSION["StartDate"]) && !isset($_SESSION["EndDate"])){
				$str = "Records from: ".date('m/j/Y')." to 08/01/2016";
			}elseif($_SESSION["SelectedGP"] != "All"){
				$str = "Grading Period: ".$_SESSION["SelectedGP"];
			}else{
				$str = "Records from: ".$_SESSION["EndDate"]." to ".$_SESSION["StartDate"];
			}
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
			$this->Ln(20);
		}
		function StudentCsTable(){
			$conn = $this->dbConnect();
			$result = $conn->query($_SESSION["sql"]);
			
			$colWidth = 75;
			$this->SetFont('Arial','B',10);
			$this->Cell($colWidth,0,'Date',0,0,'C');
			$this->Cell($colWidth,0,'Activity',0,0,'C');
			$this->Cell($colWidth,0,'Score',0,0,'C');
			$this->Cell($colWidth,0,'Items',0,0,'C');
			$this->Line(0,92,$this->GetPageWidth(),92);
			$this->Ln(10);
			
			$this->SetFont('Arial','',10);
			
			if ($result->num_rows > 0){
				while($row = $result->fetch_assoc()){
					$this->Cell($colWidth,0,$row["ActivityDate"],0,0,'C');
					$this->Cell($colWidth,0,$row["ActivityDescription"],0,0,'C');
					$this->Cell($colWidth,0,$row["Score"],0,0,'C');
					$this->Cell($colWidth,0,$row["ActivityScore"],0,0,'C');
					$this->Ln(6);
				}
			}else{
				$this->Ln(50);
				$this->Cell($this->GetPageWidth(),0,'No Records.',0,0,'C');
			}
		}
		function StudentGradesDetails(){
			$str = "Student Name: ".$_SESSION["FullName"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'L',false);
			
			$this->Cell(20);
			$str = "ID Number: ".$_SESSION["UserID"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
			
			$this->Cell(20);
			$str = "Section: ".$_SESSION["Section"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
					
			$this->Cell(20);
			$str = "Grade/Year: #";
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
			$this->Ln(20);
		}
		function StudentGradesTable(){
			$conn = $this->dbConnect();
			$sql = $_SESSION["sql"];
			$result = $conn->query($sql);
			
			$colWidth = 50;
			$this->SetFont('Arial','B',10);
			$this->Cell($colWidth,0,'SUBJECTS',0,0,'C');
			$this->Cell($colWidth,0,'First Grading',0,0,'C');
			$this->Cell($colWidth,0,'Second Grading',0,0,'C');
			$this->Cell($colWidth,0,'Third Grading',0,0,'C');
			$this->Cell($colWidth,0,'Fourth Grading',0,0,'C');
			$this->Cell($colWidth,0,'Final Grade',0,0,'L');
			$this->Line(0,92,$this->GetPageWidth(),92);
			$this->Ln();
			
			$this->SetFont('Arial','',10);
			
			$prevSubj = "";
			$genAve = "";
			while($row = $result->fetch_assoc()){
				if($row["SubjectCode"] != $prevSubj){
					$this->Ln(6);
					$this->Cell($colWidth,0,$row["SubjectDescription"],0,0,'L');
				}
				$this->Cell($colWidth,0,$row["StudentGrade"],0,0,'C');
				if($row["GradingPeriod"] == "4"){
					$genAve += $row["StudentGrade"];
					if($row["StudentGrade"] >= 75){
						$this->Cell($colWidth,0,"Passed",0,0,'L');
					}else{
						$this->Cell($colWidth,0,"Failed",0,0,'L');
					}
				}
				$prevSubj = $row["SubjectCode"];
			}
			$this->Ln(20);
			
			$genAve /= 8;
			
			$this->SetFont('Arial','B',10);
			$this->Cell(0,0,'General Average: '.$genAve,0,0,'R');
		}
		function AdviserCSAttendanceDetails(){
			$this->Ln(-15);
			$str = "Adviser: ".$_SESSION["FullName"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'L',false);
			
			$this->Cell(10);
			$str = "ID Number: ".$_SESSION["UserID"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
			
			$this->Cell(10);
			$str = "Section: ".$_SESSION["Section"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
			
			$this->Cell(10);
			$str = "Subject: ".$_SESSION["SelectedSubject"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
			
			$this->Cell(10);
			if (!isset($_SESSION["StartDate"]) && !isset($_SESSION["EndDate"])){
				$str = "Records from: ".date('m/j/Y')." to 08/01/2016";
			}elseif($_SESSION["SelectedGP"] != "All"){
				$str = "Grading Period: ".$_SESSION["SelectedGP"];
			}else{
				$str = "Records from: ".$_SESSION["EndDate"]." to ".$_SESSION["StartDate"];
			}
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
			
			$this->Ln(5);
			
		}
		function AdviserCsTable(){
			$conn = $this->dbConnect();
			$sql = $_SESSION["class_standing"][0];
			$actCount = $_SESSION["class_standing"][1];
			$result = $conn->query($sql);
			
			$ctr = 0;
			while ($row = $result->fetch_assoc()){
				$StudentID[] = $row["StudentID"];
				$StudentName[] = $row["LastName"].", ".$row["FirstName"]." ".$row["MiddleName"];
				$StudentScore[] = $row["Score"];
				$ActivityCode[] = $row["ActivityCode"];
				$ActivityScore[] = $row["ActivityScore"];
				$ActivityDates[] = $row["ActivityDate"];
				$ctr++;
			}
			/*
			$this->SetFont('Arial','B',8);
			$this->Cell(35,7,'Date',0,0,'C');
			
			$this->SetFont('Arial','',6);
			for($i=0;$i<$actCount;$i++){
				$this->StartTransform();
				$this->Rotate(0);
				#$this->SetX($this->GetX() + $actCount);
				$this->Cell(($this->GetPageWidth()-50)/$actCount,7,$ActivityDates[$i],1,0,'C');
				$this->StopTransform();
			}
			$this->Ln(7);
			#*/
			
			$this->SetFont('Arial','B',8);
			$this->Cell(35,7,'Students \ Details',1,0,'C');	
			
			$this->SetFont('Arial','B',7);
			
			for($i=0;$i<$actCount;$i++){
				$this->Cell(($this->GetPageWidth()-50)/$actCount,3.5,substr($ActivityCode[$i],0,2),1,0,'C');
			}
			$this->Ln();
			$this->Cell(35);
			for($i=0;$i<$actCount;$i++){
				$this->SetFillColor(175,175,255);
				$this->Cell(($this->GetPageWidth()-50)/$actCount,3.5,$ActivityScore[$i],1,0,'C',true);
			}
			
			$prevStud = "";
			for($i=0;$i<$ctr;$i++){
				if($StudentID[$i] != $prevStud){
					$this->Ln();
					$this->Cell(35,4,$StudentName[$i],1,0,'L');
				}
				$this->Cell(($this->GetPageWidth()-50)/$actCount,4,$StudentScore[$i],1,0,'C');
				$prevStud = $StudentID[$i];
			}
		}
		function AdviserAttendanceTable(){
			$conn = $this->dbConnect();
			$sql = $_SESSION["attendance"][0];
			$attendanceCount = $_SESSION["attendance"][1];
			$result = $conn->query($sql);
			
			$ctr = 0;
			while ($row = $result->fetch_assoc()){
				$StudentID[] = $row["StudentID"];
				$StudentName[] = $row["LastName"].", ".$row["FirstName"]." ".$row["MiddleName"];
				$StudentAttendance[] = $row["AttendanceDescription"][0];
				$AttendanceDates[] = $row["AttendanceDate"];
				$ctr++;
			}
			
			$this->SetFont('Arial','B',7);
			$this->Cell(30,7,'Students \ Date',1,0,'C');	
			
			$this->SetFont('Arial','B',5);
			
			$prevStud = "";
			for($i=0;$i<$attendanceCount;$i++){
				$this->Cell(($this->GetPageWidth()-50)/$attendanceCount,7,$AttendanceDates[$i],1,0,'C');
			}
			for($i=0;$i<$ctr;$i++){
				if($StudentID[$i] != $prevStud){
					$this->Ln();
					$this->Cell(30,4,$StudentName[$i],1,0,'L');
				}
				$this->Cell(($this->GetPageWidth()-50)/$attendanceCount,4,$StudentAttendance[$i],1,0,'C');
				$prevStud = $StudentID[$i];
			}
		}
		function AdviserGradesDetails(){
			$this->Ln(-15);
			$str = "Adviser: ".$_SESSION["FullName"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'L',false);
			
			$this->Cell(10);
			$str = "ID Number: ".$_SESSION["UserID"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
			
			$this->Cell(10);
			$str = "Section: ".$_SESSION["Section"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
			
			$this->Cell(10);
			$str = "Subject: ".$_SESSION["SelectedSubject"];
			$this->Cell($this->GetStringWidth($str),0,$str,0,0,'',false);
			
			$this->Ln(5);
		}
		function AdviserGradesTable(){
			$conn = $this->dbConnect();
			$sql = $_SESSION["sql"];
			$result = $conn->query($sql);
			
			$colWidth = ($this->GetPageWidth()-20)/6;
			$this->Ln();
			$this->SetFont('Arial','B',10);
			$this->Cell($colWidth,5,'Student',1,0,'C');
			$this->Cell($colWidth,5,'First Grading',1,0,'C');
			$this->Cell($colWidth,5,'Second Grading',1,0,'C');
			$this->Cell($colWidth,5,'Third Grading',1,0,'C');
			$this->Cell($colWidth,5,'Fourth Grading',1,0,'C');
			$this->Cell($colWidth,5,'Final Grade',1,0,'C');
			
			$this->SetFont('Arial','',9);
			$prevStud = "";
			while ($row = $result->fetch_assoc()){
				if($row["UserID"] != $prevStud){
					$this->Ln();
					$this->Cell($colWidth,5,$row["StudentName"],1,0,'L');
				}
				$this->Cell($colWidth,5,$row["StudentGrade"],1,0,'C');
				if($row["GradingPeriod"] == 4){
					if ($row["StudentGrade"] >= 75){
						$this->Cell($colWidth,5,'PASSED',1,0,'C');
					}else{
						$this->Cell($colWidth,5,'FAILED',1,0,'C');
					}
				}
				$prevStud = $row["UserID"];
			}
		}
	}
	$pdf = new FPDF('P','in',array(8,13));
	$pdf = new PDF();
	$pdf->AliasNbPages();
	$pdf->AddPage('L');
	if ($_SESSION["UserType"] == "Student"){
		if ($_SESSION["formtype"] == "Attendance"){
			$pdf->StudentAttendanceDetails();
			$pdf->StudentAttendanceTable();
		}
		elseif ($_SESSION["formtype"] == "Class Standing"){
			$pdf->StudentCsDetails();
			$pdf->StudentCsTable();
		}
		elseif ($_SESSION["formtype"] == "Grades"){
			$pdf->StudentGradesDetails();
			$pdf->StudentGradesTable();
		}
	}elseif($_SESSION["UserType"] == "Adviser"){
		if ($_SESSION["formtype"] == "Attendance"){
			$pdf->AdviserCSAttendanceDetails();
			$pdf->AdviserAttendanceTable();
		}elseif($_SESSION["formtype"] == "Class Record"){
			$pdf->AdviserCSAttendanceDetails();
			$pdf->AdviserCsTable();
		}
		elseif ($_SESSION["formtype"] == "Grades"){
			$pdf->AdviserGradesDetails();
			$pdf->AdviserGradesTable();
		}
	}
	$pdf->Output();
?>